"""Initial database schema

Revision ID: d315bca502bb
Revises: 
Create Date: 2025-07-03 01:04:49.866767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd315bca502bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('vehicle_verifications',
    sa.Column('reg_no', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('reg_no')
    )
    op.create_index(op.f('ix_vehicle_verifications_reg_no'), 'vehicle_verifications', ['reg_no'], unique=False)
    op.create_table('vehicle_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.Enum('car', 'bike', name='vehicletypeenum'), nullable=True),
    sa.Column('kilometers_driven', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('usr_inp_city', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('seller_phone', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reg_no', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reg_no'], ['vehicle_verifications.reg_no'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_listings_id'), 'vehicle_listings', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_listings_usr_inp_city'), 'vehicle_listings', ['usr_inp_city'], unique=False)
    op.create_index(op.f('ix_vehicle_listings_vehicle_type'), 'vehicle_listings', ['vehicle_type'], unique=False)
    op.create_table('listing_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['vehicle_listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_images_id'), 'listing_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_images_id'), table_name='listing_images')
    op.drop_table('listing_images')
    op.drop_index(op.f('ix_vehicle_listings_vehicle_type'), table_name='vehicle_listings')
    op.drop_index(op.f('ix_vehicle_listings_usr_inp_city'), table_name='vehicle_listings')
    op.drop_index(op.f('ix_vehicle_listings_id'), table_name='vehicle_listings')
    op.drop_table('vehicle_listings')
    op.drop_index(op.f('ix_vehicle_verifications_reg_no'), table_name='vehicle_verifications')
    op.drop_table('vehicle_verifications')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
